kind: Service
apiVersion: v1
metadata:
  name: mule-hello-service
  labels:
    app: mule-hello
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: mule-hello
