apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mule-hello
spec:
  selector:
    matchLabels:
      app: mule-hello
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: mule-hello
        tier: frontend
    spec:
      containers:
      - name: mule-hello
        image: docker.io/lindstedt/mule-hello:1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 8081
